# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1)),
                ('identification_number', models.CharField(max_length=18)),
                ('phone_number', models.CharField(max_length=11)),
                ('department', models.CharField(choices=[('KYC', '科研管理处'), ('KYTJ', '科研条件处'), ('RJC', '人事教育处')], max_length=4)),
                ('sector', models.CharField(choices=[('GL', '管理片'), ('GY', '光源片'), ('HN', '核能片')], max_length=2)),
                ('is_valid', models.CharField(choices=[('ZG', '在岗'), ('LZ', '离职'), ('BY', '毕业'), ('LG', '调离岗位')], default='ZG', max_length=2)),
            ],
        ),
    ]
