# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(choices=[('SH', '上海市级'), ('GC', '国家初级'), ('GZ', '国家中级')], max_length=2, verbose_name='培训类型')),
                ('training_orgnization', models.CharField(max_length=20)),
                ('date_training', models.DateTimeField(verbose_name='培训日期')),
                ('date_expired', models.DateTimeField(verbose_name='有效期至')),
                ('certification_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('KYC', '科研管理处'), ('KYTJ', '科研条件处'), ('RJC', '人事教育处')], max_length=4, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='identification_number',
            field=models.CharField(max_length=18, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_valid',
            field=models.CharField(choices=[('ZG', '在岗'), ('LZ', '离职'), ('BY', '毕业'), ('LG', '调离岗位')], default='ZG', max_length=2, verbose_name='在岗情况'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=32, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sector',
            field=models.CharField(choices=[('GL', '管理片'), ('GY', '光源片'), ('HN', '核能片')], max_length=2, verbose_name='所属片区'),
        ),
        migrations.AddField(
            model_name='certification',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_management.Profile'),
        ),
    ]
