# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 05:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_management', '0002_auto_20170926_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certification',
            old_name='training_orgnization',
            new_name='training_organization',
        ),
        migrations.AlterField(
            model_name='certification',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_management.Profile'),
        ),
    ]
