# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_management', '0003_auto_20170926_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='certification_number',
            field=models.CharField(max_length=20, verbose_name='证书编号'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='training_organization',
            field=models.CharField(max_length=20, verbose_name='培训机构'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_management.Profile'),
        ),
    ]
